machine:
  python:
    version: 2.7.13
dependencies:
  post:
    - pip install flake8 --upgrade
    - pip install -r requirements.txt --upgrade
test:
  override:
    - flake8 .
    - python -m unittest -v tests
    - pyenv global 3.6.1
    - pip3 install flake8 --upgrade
    - pip3 install -r requirements.txt --upgrade
    - flake8 .
    - python -m unittest -v tests