version: 2

workflows:
  version: 2
  tests:
    jobs:
      - test-3.7
      - test-3.6
      - test-3.5
      - test-2.7

jobs:
  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            cd ~/repo/
            pip install -r requirements.txt --upgrade

      - run:
          name: Install Flake
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install flake8 --upgrade

      - run:
          name: Run flake8
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            cd ~/repo/
            python -m flake8 --config=tox.ini ./imaplibext/

  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6.6

  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5.5

  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7.15